cmake_minimum_required(VERSION 3.31)
project(main_cmake)

set(CMAKE_CXX_STANDARD 20)

add_executable(
        main_cmake
#        YaP/ya_olimp.cpp
#        main.cpp
#        YaP/lecture/main.cpp
#        testo.cpp
#        Ent.h
#        cm_math.cpp
#        matrix_nxn.h
#        YaP/1.cpp
#        YaP/2.cpp
#        YaP/_2.cpp
#        YaP/3.cpp
#        YaP/4.cpp
#        YaP/5.cpp
#        YaP/6.cpp
#        YaP/7.cpp
#        "YaP/_7#.cpp"
#        YaP/8.cpp
#        YaP/9.cpp
#        YaP/10.cpp
        YaP/11.cpp
 #        YaP/12.cpp
#        YaP/13.cpp

)
