cmake_minimum_required(VERSION 3.31)
project(main_cmake)

set(CMAKE_CXX_STANDARD 20)

add_executable(
        main_cmake
#        main.cpp
#        testo.cpp
#        Ent.h
#        cm_math.cpp
#        matrix_nxn.h
#        YaP/1.cpp
#        YaP/2.cpp
#        YaP/3.cpp
        YaP/4.cpp
#        YaP/6.cpp
)
