cmake_minimum_required(VERSION 3.31)
project(main_cmake)

set(CMAKE_CXX_STANDARD 20)

add_executable(
        main_cmake
#        YaP/ya_olimp.cpp
#        YaP/lecture/main.cpp
#        "YaP/1st course/1.cpp"
#        "YaP/1st course/2.cpp"
#        "YaP/1st course/_2.cpp"
#        "YaP/1st course/3.cpp"
#        "YaP/1st course/4.cpp"
#        "YaP/1st course/5.cpp"
#        "YaP/1st course/6.cpp"
#        YaP/lecture/llu_overflow.cpp
#        "YaP/1st course/7.cpp"
#        "YaP/1st course/_7#.cpp"
#        "YaP/1st course/8.cpp"
#        "YaP/1st course/9.cpp"
        "YaP/1st course/10.cpp"
#        "YaP/1st course/11.cpp"
#        "YaP/1st course/12.cpp"
#        "YaP/1st course/13.cpp"

)
